#!/usr/bin/env python3
"""Refine the Block-1 sensitivity comparison from h=0.0125 to h=0.00625.

`compare_runtime_to_exact.py` (Block 1A) already computes and stores the exact
Jacobian plus the source-faithful FreeFlux Jacobian at h=0.0125 in
`results/sensitivity_matrices.npz`.  This script reuses that exact Jacobian and
computes only the h=0.00625 runtime Jacobian, then stores
`results/sensitivity_h0.00625.npz`.  The summary CSV/JSON used by the manuscript
is regenerated by `make_block1_deliverables.py`.
"""
from pathlib import Path
import sys, time
import numpy as np

ROOT = Path(__file__).resolve().parent
OUT = ROOT / 'results'
sys.path.insert(0, str(ROOT))
import compare_runtime_to_exact as c

base = np.load(OUT / 'sensitivity_matrices.npz', allow_pickle=True)
J_exact = base['J_exact']
names = base['parameter_names'].astype(str)
if list(names) != list(c.PARAM_NAMES):
    raise RuntimeError('Parameter ordering mismatch between Block 1A and refinement')

model, sim = c.runtime_model()
step = 0.00625
grid = c.make_grid(step)
print(f'runtime Jacobian refinement: h={step:g}, n_timepoints={len(grid)}')
t0 = time.time()
fun = lambda th: c.runtime_output(model, sim, th, grid)
J_runtime = c.finite_difference(fun, c.theta0, h=1e-5, drop_last=True)
elapsed = time.time() - t0

if J_runtime.shape != J_exact.shape:
    raise RuntimeError(f'Jacobian shape mismatch: runtime={J_runtime.shape}, exact={J_exact.shape}')

d = J_runtime - J_exact
max_abs = float(np.max(np.abs(d)))
rms = float(np.sqrt(np.mean(d*d)))
rel_f = float(np.linalg.norm(d) / np.linalg.norm(J_exact))
per = []
for j, name in enumerate(c.PARAM_NAMES):
    rel = float(np.linalg.norm(d[:, j]) / max(np.linalg.norm(J_exact[:, j]), 1e-300))
    per.append((name, rel))
worst_name, worst_rel = max(per, key=lambda x: x[1])

np.savez_compressed(
    OUT / 'sensitivity_h0.00625.npz',
    J_exact=J_exact,
    J_runtime=J_runtime,
    parameter_names=np.asarray(c.PARAM_NAMES),
)

print(f'elapsed_seconds={elapsed:.6f}')
print(f'global_max_abs={max_abs:.16e}')
print(f'global_rms={rms:.16e}')
print(f'relative_Frobenius={rel_f:.16e}')
print(f'worst_parameter={worst_name}')
print(f'worst_relative_L2={worst_rel:.16e}')
